item {
    id: 1
    name: 'one'
}

item {
    id: 2
    name: 'two'
}
item {
    id: 3
    name: 'three'
}

item {
    id: 4
    name: 'four'
}
item {
    id: 5
    name: 'five'
}
item {
    id: 6
    name: 'six'
}

item {
    id: 7
    name: 'arrow_left'
}
item {
    id: 8
    name: 'arrow_right'
}
item {
    id: 9
    name: 'arrow_up'
}
item {
    id: 10
    name: 'arrow_down'
}

item {
    id: 11
    name: 'denied'
}

item {
    id: 12
    name: '0_degree'
}

item {
    id: 13
    name: '45_degree'
}
item {
    id: 14
    name: '90_degree'
}
item {
    id: 15
    name: '180_degree'
}
item {
    id: 16
    name: 'checkpoint_signal'
}
item {
    id: 17
    name: 'checkpoint_side'
}
item {
    id: 18
    name: 'checkpoint_foot'
}
item {
    id: 19
    name: 'wall'
}
